### ISSUE TITLE
Implement --clearmodifiers

### ISSUE THREAD

**Issue by iberianpig** [iberianpig/fusuma-plugin-sendkey#1]
**Describe the bug**

Currently, the following trigger does not work with [fusuma-plugin-keypress](https://github.com/iberianpig/fusuma-plugin-keypress).

```yaml
hold:
  3:
    keypress:
      LEFTALT:
        sendkey: "LEFTALT+F7"  # OK
      LEFTMETA:
        sendkey: "LEFTALT+F7" # NG
```

**Expected behavior**

`fusuma-plugin-sendkey` should have an option like `--clearmodifier` of xdotool.

it should work following ~/.config/fusuma/config.yml

```yaml
hold:
  3:
    keypress:
      LEFTMETA:
        sendkey: "--clearmodifier LEFTALT+F7"
```

CLI
```sh
$ fusuma-sendkey --clearmodifier LEFTALT+F7
```
