### ISSUE TITLE
Keyboard name not working?

### ISSUE THREAD

**Issue by jaimeagudo** [iberianpig/fusuma-plugin-sendkey#12]
```
 : Fusuma: 1.11.1
  INFO -- : libinput: 1.15.5
  INFO -- : OS: Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
  INFO -- : Distribution: Ubuntu 20.04.1 LTS \n \l
  INFO -- : Desktop session:
  INFO -- : -----------------------------------------
```

On Ubuntu I am trying to get the typical Mac *expose* swipping up with 3 fingers, I can emulate that with xdotool and xte but fusuma does nothing despite recognizing the command, I can see the gesture is recognized just fine on the log and the commands work on the terminal but nothing happens, some wire is disconnected after running the "command" part so trying with fusuma-send-key but I got 

I am getting

`sendkey: Keyboard: /keyboard|Keyboard|KEYBOARD/ is not found`

As per 
`$  sudo libinput list-devices` 

```
Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event3
Group:            9
Seat:             seat0, default
Capabilities:     keyboard

```

I guess ` AT Translated Set 2 keyboard` is my _keyboard name_ so I put it on config.yml

```
plugin:
  executors:
    sendkey_executor:
      device_name: 'AT Translated Set 2 keyboard'
      #device_name: '/sys/class/input/input3/name'

swipe:
  3:
    up:
      command: ' xte "keydown Super_L" "key space"'
```
It does not make any difference, what am I missing? I tried adding the device path but it doesn't work, sorry but I find this bit missing on the docs. Thanks in advance

I don't add the fusuma-sendkey equivalent cause It won't work
