### ISSUE TITLE
pinch to zoom

### ISSUE THREAD

**Issue by sergiupopescu199** [iberianpig/fusuma-plugin-sendkey#13]
Hi, I have some problems making zoom in/out using the sendkey plugin, using LEFTCTRL+KPPLUS and LEFTCTRL+KPMINUS is working but if I insert the command in the pinch section in the config.yml is not working. I'm using KDE Plasma. Could you help me understand ho to make it work? I not instakked xdotools, I must install it?

Thanks in advance

**Comment by iberianpig** [comment]
Could you paste output of your config.yml?

**Comment by HritwikSinghal** [comment]
hey @iberianpig , i am having similar issue, ```ZOOMIN``` and ```ZOOMOUT``` does not work in apps like firefox or any other app ( it logs ```I, [2021-04-13T10:30:15.031871 #1711537]  INFO -- : {:sendkey=>"ZOOMIN"}``` but does nothing) but ```sendkey: "LEFTCTRL+KPPLUS"``` works fine.


This is my config 
```
pinch:
  in:
    sendkey: "ZOOMIN" # This does not work
    sendkey: "LEFTCTRL+KPPLUS" # This works
  out:
    # sendkey: "ZOOMOUT" # Zoom out
    sendkey: "LEFTCTRL+KPMINUS" # Zoom out


threshold:
  pinch: 0.8

interval:
  pinch: 1.5
```
