### ISSUE TITLE
sendkey combine with keypress

### ISSUE THREAD

**Issue by tkuwill** [iberianpig/fusuma-plugin-sendkey#22]
```yaml
swipe:
  3: 
    left: 
      command: 'xdotool key ctrl+Page_Up'  
      keypress:
        LEFTSHIFT:
          command: 'xdotool key alt+right' # forth          
    right: 
      command: 'xdotool key ctrl+Page_Down'
      keypress:
        LEFTSHIFT:
          command: 'xdotool key alt+left' # back       
```
At first, I use sendkey: "LEFTALT+LEFT"  at the line now is "command: 'xdotool key alt+left' # back "  , 
 sendkey: "LEFTALT+RIGHT"  at the line now is "command: 'xdotool key alt+right' # forth " .   However, both of them can't work on Firefox to get page back or forth. Is there any solution to that ? my system is Ubuntu 20.04 LTS, in an macbook air 2015.  Thanks!

**Comment by iberianpig** [comment]
## Use sendkey with updating Fusuma

Have you updated to fusuma v2? 
In Fusuma v2, the integration between Keypress and Sendkey has been tuned.

Please try to update fusuma and plugins.

```sh
$ sudo gem update fusuma fusuma-plugin-sendkey fusuma-plugin-keypress
```

I tried the following settings and it worked fine.

```yaml
swipe:
  3: 
    left: 
      sendkey: 'LEFTCTRL+PAGEUP'
      keypress:
        LEFTSHIFT:
          sendkey: 'LEFTALT+RIGHT'
    right: 
      sendkey: 'LEFTCTRL+PAGEDOWN'
      keypress:
        LEFTSHIFT:
          sendkey: 'LEFTALT+LEFT'
```


## To use xdotool

1. You should try xdotool command in your terminal.
Your `xdotool key alt+left` is invalid syntax.

```sh
$ xdotool key alt+left
(symbol) No such key name 'left'. Ignoring it.
(symbol) No such key name 'left'. Ignoring it.
```

Please use Left/Right(Upper case)

```sh
$ xdotool key alt+Left
```

2. Since you are holding down the Shift key, Firefox will receive Shift + Alt + Left.

In this case, fusuma-plugin-sendkey works fine; it will only send the Alt and Left keys.

In xdotool, use the `--clearmodifiers` option. Like `xdotool key --clearmodifiers alt+Left`.
