### ISSUE TITLE
My sendkey dosenot work! 

### ISSUE THREAD

**Issue by luyanfeng** [iberianpig/fusuma-plugin-sendkey#32]
My sendkey dosenot work! 

console has log, bug it dosenot work:
![图片](https://github.com/iberianpig/fusuma-plugin-sendkey/assets/5779510/59801e21-babf-42fb-b698-04bc3d3426f3)

My config :
```yaml

pinch:
  2:  
    in: 
      #command: "xdotool keydown ctrl click 4 keyup ctrl" 
       #command: "ydotool key 29:1 12:1 12:0 29:0"
      sendkey: "LEFTCTRL+MINUS"
      threshold: 0.5 
      interval: 0.5 
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" 
        #command: "ydotool key 29:1 13:1 13:0 29:0"
      sendkey: "LEFTCTRL+EQUAL"
      threshold: 0.5 
      interval: 0.5
```
