### ISSUE TITLE
PLUS key unsupported

### ISSUE THREAD

**Issue by Kangie** [iberianpig/fusuma-plugin-sendkey#4]
The PLUS key is unsupported, making it hard to configure pinch to zoom (etc).

`fusuma-sendkey LEFTCTRL+PLUS
Did you mean? KPPLUS / KPPLUSMINUS
sendkey: PLUS is unsupported.`

KPPLUS and KPPLUSMINUS do not zoom.
 
My current workaround is to use xdotool for pinch to zoom, however I'd like to be able to replace all command: with sendkey: so that my config is consistent (and I can hopefully remove xdotool from my system).

**Comment by hazgon** [comment]
> KPPLUS and KPPLUSMINUS do not zoom.

Try to use this way:
```
pinch:
   2:
     in:
       sendkey: "LEFTCTRL+KPPLUS" 
     out:
       sendkey: "LEFTCTRL+KPMINUS"
```
This works for me
