### ISSUE TITLE
sendkey gestures not recognised (Ubuntu 24.04)

### ISSUE THREAD

**Issue by Nandete84** [iberianpig/fusuma-plugin-sendkey#40]
Hi,
I've just upgraded to the latest Ubuntu 24.04 LTS and I had to reinstall fusuma, amending the config file to use sendkey:

```
swipe:
  3: 
    left: 
      sendkey:  "HOMEPAGE,RIGHT" # Maximize a window vertically along the right side of the screen
      clearmodifiers: true
    right: 
      sendkey:  "HOMEPAGE,LEFT" # Maximize a window vertically along the left side of the screen
      clearmodifiers: true
    up: 
      sendkey:  "HOMEPAGE,UP" # Maximize a window
      clearmodifiers: true
    down: 
      sendkey:  "HOMEPAGE,H" # Minimize a window
      clearmodifiers: true
  4:
    left:
      sendkey: "LEFTCTRL+LEFTALT+LEFT" # Switch to previous workspace
      clearmodifiers: true
    right:
      sendkey: "LEFTCTRL+LEFTALT+RIGHT" # Switch to next workspace
      clearmodifiers: true
    up:
      sendkey: "HOMEPAGE+A" # Show Apps
      clearmodifiers: true
    down:
      sendkey: "HOMEPAGE+D" # Hide all normal windows
      clearmodifiers: true
pinch:
  in:
    sendkey:  "LEFTCTRL+LEFTSHIFT+underscore" # Zoom out
    clearmodifiers: true
  out:
    sendkey:  "LEFTCTRL+LEFTSHIFT+0" #Zoom in
    clearmodifiers: true
hold:
  4:
    sendkey: "HOMEPAGE" # Windows overview
    clearmodifiers: true
```
(I added the clearmodifiers after a few tries, but still same result)
So, after rebooting, fusuma is not working, and when run it on the terminal I get these:

`sendkey: HOMEPAGE,H is unsupported.`
`sendkey: HOMEPAGE,UP is unsupported.`
`sendkey: HOMEPAGE,RIGHT is unsupported.`
`sendkey: HOMEPAGE,LEFT is unsupported.`

Thing is, when I list the keys on sendkey, those are available, and I tried with the keyboard that they are the correct combination.

Clearly I am missing somenthing.

Glad if anyone could help.

Thanks in advance.

**Comment by iberianpig** [comment]
Could you paste output of `libinput list-devices` ?

**Comment by iberianpig** [comment]
The issue might be resolved by specifying multiple key presses in Array format instead of a comma-separated String, like this:

```diff
swipe:
  3: 
    left: 
-      sendkey:  "HOMEPAGE,RIGHT" # Maximize a window vertically along the right side of the screen
+      sendkey:  [HOMEPAGE, RIGHT] # Maximize a window vertically along the right side of the screen
```

**Comment by Nandete84** [comment]
Hi,
```

Device:           Power Button
Kernel:           /dev/input/event3
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           Video Bus
Kernel:           /dev/input/event10
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           Video Bus
Kernel:           /dev/input/event9
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           Lid Switch
Kernel:           /dev/input/event0
Group:            4
Seat:             seat0, default
Capabilities:     switch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           Sleep Button
Kernel:           /dev/input/event2
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           Trust Wireless Mouse
Kernel:           /dev/input/event7
Group:            6
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   flat *adaptive custom
Rotation:         0.0

Device:           Ideapad extra buttons
Kernel:           /dev/input/event8
Group:            7
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           HDA Intel PCH Headphone
Kernel:           /dev/input/event12
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event4
Group:            9
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

Device:           ETPS/2 Elantech Touchpad
Kernel:           /dev/input/event5
Group:            10
Seat:             seat0, default
Size:             98x61mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```

I already tried the config with the multiple key presses and still it doen't work, but I don't have any error message...

Weird...

**Comment by tsids** [comment]
I have a similar problem in Arch with KDE Plasma 6, X11

Everything works fine, except for the "LEFTMETA+PAGEUP" command. 

When I send the command `fusuma-sendkey "LEFTMETA+PAGEUP"` through the terminal, it gives the correct response i.e. maximizing/restoring the window.

 I'm not sure why it doesn't work when I add it to the config though.

```
swipe:
  3:
    up:
      sendkey: "LEFTMETA+PAGEUP" # maximize window
    down:
      sendkey: "LEFTMETA+PAGEUP" # restore window
    begin:
      command: xdotool keydown Alt
    right:
      update:
        command: xdotool key Tab # switch window
        interval: 5
    left:
      update:
        command: xdotool key Shift+Tab # switch window back
        interval: 5
    end:
      command: xdotool keyup Alt
  4:
    up:
      command: "xdotool key super+w"
    down:
      command: "xdotool key super+w"
pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" # zoom in
      threshold: 0.5
      interval: 0.5
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # zoom out
      threshold: 0.5
      interval: 0.5
```
