### ISSUE TITLE
Fusuma works, Fusuma-Plugin-Sendkey works, But nothing happens

### ISSUE THREAD

**Issue by titaniumjones** [iberianpig/fusuma-plugin-sendkey#9]
I've installed Fusuma and XDOTools and managed to get the multi-touch system working just fine. So I thought I'd try your send key plugin instead of the XDOTools. This raised lead to the Keyboard update from last night.
Now your SendKey plugin works for me, however nothing actually happens in Ubuntu. I must also comment that the keystrokes do actually perform the indicated actions, it's just nothing happens when using the trackpad.

Here is a grab of the terminal output:
```
titaniumjones@Foxy:~$ fusuma
I, [2020-07-14T09:14:39.052636 #14763]  INFO -- : ---------------------------------------------
I, [2020-07-14T09:14:39.052683 #14763]  INFO -- : Fusuma: 1.10.1
I, [2020-07-14T09:14:39.055202 #14763]  INFO -- : libinput: 1.15.5
I, [2020-07-14T09:14:39.056358 #14763]  INFO -- : OS: Linux 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020
I, [2020-07-14T09:14:39.057399 #14763]  INFO -- : Distribution: Ubuntu 20.04 LTS \n \l
I, [2020-07-14T09:14:39.058366 #14763]  INFO -- : Desktop session: ubuntu x11
I, [2020-07-14T09:14:39.058395 #14763]  INFO -- : ---------------------------------------------
I, [2020-07-14T09:14:39.058687 #14763]  INFO -- : Enabled Plugins: 
I, [2020-07-14T09:14:39.058756 #14763]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2020-07-14T09:14:39.058781 #14763]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2020-07-14T09:14:39.058795 #14763]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2020-07-14T09:14:39.058818 #14763]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2020-07-14T09:14:39.058852 #14763]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2020-07-14T09:14:39.058870 #14763]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2020-07-14T09:14:39.058891 #14763]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2020-07-14T09:14:39.058908 #14763]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2020-07-14T09:14:39.058929 #14763]  INFO -- :   Fusuma::Plugin::Executors::SendkeyExecutor
I, [2020-07-14T09:14:39.058946 #14763]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2020-07-14T09:14:39.058966 #14763]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2020-07-14T09:14:39.058981 #14763]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2020-07-14T09:14:39.058998 #14763]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2020-07-14T09:14:39.059022 #14763]  INFO -- : ---------------------------------------------
I, [2020-07-14T09:14:39.059615 #14763]  INFO -- : reload config : /home/titaniumjones/.config/fusuma/config.yml
I, [2020-07-14T09:14:40.662291 #14763]  INFO -- : {:sendkey=>"LEFTMETA"}
I, [2020-07-14T09:14:41.727131 #14763]  INFO -- : {:sendkey=>"LEFTALT+LEFT"}
I, [2020-07-14T09:14:44.264867 #14763]  INFO -- : {:sendkey=>"LEFTMETA"}
I, [2020-07-14T09:14:47.127935 #14763]  INFO -- : {:sendkey=>"LEFTMETA"}
I, [2020-07-14T09:14:50.048448 #14763]  INFO -- : {:sendkey=>"LEFTALT+RIGHT"}
I, [2020-07-14T09:14:56.729506 #14763]  INFO -- : {:sendkey=>"LEFTCTRL+LEFTALT+UP"}
I, [2020-07-14T09:14:57.946522 #14763]  INFO -- : {:sendkey=>"LEFTCTRL+LEFTALT+DOWN"}
I, [2020-07-14T09:14:58.889035 #14763]  INFO -- : {:sendkey=>"LEFTCTRL+LEFTALT+DOWN"}
I, [2020-07-14T09:14:59.903501 #14763]  INFO -- : {:sendkey=>"LEFTCTRL+LEFTALT+UP"}
```
Here is a grab of the config file:
```
swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT" # History forward 
    right:
      sendkey: "LEFTALT+LEFT" # History back
    up:
      sendkey: "LEFTMETA" # Activity
    down:
      sendkey: "LEFTMETA" # Activity
  4:
    left:
      sendkey: "LEFTCTRL+LEFTALT+DOWN" # Switch to next workspace
    right:
      sendkey: "LEFTCTRL+LEFTALT+UP" # Switch to previous workspace
    up:
      sendkey: "LEFTCTRL+LEFTALT+UP" # Switch to next workspace
    down:
      sendkey: "LEFTCTRL+LEFTALT+DOWN" # Switch to previous workspace

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
```
